project_name: kured
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kured
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

snapshot:
  name_template: "{{ .ShortCommit }}"

release:
  disable: true

changelog:
  skip: true
