name: Verify GoReleaser config
on:
  pull_request:
    paths:
      - '.config/goreleaser.yaml'
  push:
    paths:
      - '.config/goreleaser.yaml'

jobs:
  check-goreleaser-config:
    name: Check GoReleaser config
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 #v7.2.3
        with:
          version: '~> v2'
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}