name: Verify GoReleaser config
on:
  pull_request:
    paths:
      - '.config/goreleaser.yaml'
  push:
    paths:
      - '.config/goreleaser.yaml'

jobs:
  check-goreleaser-config:
    name: Check GoReleaser config
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 #v7.2.2
        with:
          version: '~> v2'
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}